locale: "en-US"
site_theme: "default"

title: "Xiaolong Han"
title_separator: "-"
name: "Xiaolong Han"
description: "Ph.D. student at the University of Surrey"
url: "https://xiaolonghan2000.github.io"
baseurl: ""
repository: "xiaolonghan2000/xiaolonghan2000.github.io"

author:
  avatar: "profile.jpg"
  name: "Xiaolong Han"
  bio: "Ph.D. student at the University of Surrey"
  location: "Guildford, Surrey, UK"
  employer: "University of Surrey"
  email: "xiaolong.han@surrey.ac.cn"
  arxiv:
  googlescholar: "https://scholar.google.com/citations?user=5oaBR_0AAAAJ"
  orcid: "https://orcid.org/0009-0009-0276-7874"
  WebofScience: "https://webofscience.clarivate.cn/wos/author/record/32992588"
  github: "xiaolonghan2000"
  linkedin:
  uri:

breadcrumbs: false
read_more: "disabled"

comments:
  provider: false

atom_feed:
  hide: true

analytics:
  provider: false

include:
  - .htaccess
  - _pages

exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - vendor
  - Gemfile.lock

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/London

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
